global:
  scrape_interval:     3s

  external_labels:
      monitor: 'app'

rule_files:

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['0.0.0.0:23333']

  - job_name: 'example'

    dns_sd_configs:
      - names: ['app']
        port: 23333
        type: A
        refresh_interval: 5s
